### PR TITLE
PR. Exception’s handling

### LINKED ISSUE #5: Exception’s handling
Server should correctly process cases when client provides incorrect information. For example, client send http request GET http://localhost:8080/api/projects/111 where 111 is ID of project, but now such project doesn't exist in the database. In this case server should return 404 response code with message: "Project with id='111' not found". No error is appeared on server logs.

### PR DESCRIPTION
**Pull request by tempo92**
Closes #5

### CODE REVIEW

File: src/main/java/org/tempo/springEdu/contoller/ProjectController.java [hunk 1]
```diff
@@ -37,33 +37,27 @@ String home() {
...
-        } else {
-            projectService.update(id, dto);
-            return new ResponseEntity<>(HttpStatus.OK);
-        }
+        Project optionalProject = projectService.findById(id);
+        projectService.update(optionalProject.getId(), dto);
+        return new ResponseEntity<>(HttpStatus.OK);
+    }
+
+    @ExceptionHandler({ProjectNotFoundException.class})
```
Comment (iv21dk) [inline src/main/java/org/tempo/springEdu/contoller/ProjectController.java:58]: It would be better if you created a new bean like this `ExceptionHandler` and move the method to there.

File: src/main/java/org/tempo/springEdu/exception/ProjectNotFoundException.java [hunk 2]
```diff
@@ -0,0 +1,9 @@
+package org.tempo.springEdu.exception;
+
+public class ProjectNotFoundException extends RuntimeException {
```
Comment (iv21dk) [inline src/main/java/org/tempo/springEdu/exception/ProjectNotFoundException.java:3]: I suggest to use more general exception name `ObjectNotFoundExceptin` because otherwise you will need to create the similar exception for each new type of entity and you will need to handle each such excrption.

File: src/main/java/org/tempo/springEdu/contoller/ProjectController.java [hunk 3]
```diff
@@ -37,33 +37,27 @@ String home() {
...
     @DeleteMapping(value = "/{id}")
     public ResponseEntity<?> delete(@PathVariable(value = "id") String id) {
-        Optional<Project> delProject = projectService.findById(id);
-        if (delProject.isEmpty()) {
-            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
-        } else {
-            projectService.delete(delProject.get());
-            return new ResponseEntity<>(HttpStatus.OK);
-        }
+        Project delProject = projectService.findById(id);
```
Comment (iv21dk) [inline src/main/java/org/tempo/springEdu/contoller/ProjectController.java:45]: For me, it would be better if you also moved `Project dev Project = project Service.findById(id);` to service method

File: src/main/java/org/tempo/springEdu/contoller/ProjectController.java [hunk 4]
```diff
@@ -37,33 +37,27 @@ String home() {
...
     public ResponseEntity<?> update(
             @PathVariable(value = "id") String id, @RequestBody ProjectUpdateDto dto) {
-        Optional<Project> optionalProject = projectService.findById(id);
-        if (optionalProject.isEmpty()) {
-            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
-        } else {
-            projectService.update(id, dto);
-            return new ResponseEntity<>(HttpStatus.OK);
-        }
+        Project optionalProject = projectService.findById(id);
```
Comment (iv21dk) [inline src/main/java/org/tempo/springEdu/contoller/ProjectController.java:53]: For me, it would be better if you also moved `Project optionalProject = projectService.findById(id);` to service method

**Review by iv21dk — CHANGES_REQUESTED** [review]

File: src/main/java/org/tempo/springEdu/service/ProjectService.java [hunk 5]
```diff
@@ -28,13 +28,15 @@ public void delete(Project project) {
         repository.delete(project);
     }
 
-    public Optional<Project> findById(String id) {
-        return repository.findById(id);
+    public Project findById(String id) {
+        return repository.findById(id)
```
[the remark this answers is not in the document]
Comment (tempo92) [reply src/main/java/org/tempo/springEdu/service/ProjectService.java:34]: Fixed

File: src/main/java/org/tempo/springEdu/contoller/ProjectController.java (hunk 1 above)
Comment (tempo92) [reply src/main/java/org/tempo/springEdu/contoller/ProjectController.java]: Fixed

File: src/main/java/org/tempo/springEdu/exception/ProjectNotFoundException.java (hunk 2 above)
Comment (tempo92) [reply src/main/java/org/tempo/springEdu/exception/ProjectNotFoundException.java]: Fixed

File: src/main/java/org/tempo/springEdu/contoller/ProjectController.java (hunk 4 above)
Comment (tempo92) [reply src/main/java/org/tempo/springEdu/contoller/ProjectController.java]: Fixed

**Review by iv21dk — APPROVED** [review]
