### PR TITLE
PR. Validation of dto objects before processing

### LINKED ISSUE #6: Validation of dto objects before processing
We need to check that client sent correct request body for methods:
•	POST /api/projects
•	PUT /api/projects/{project-id}
The body is considered as correct if the field "name" is filled (not null and not empty string).
If the request body is incorrect, server should return code 400 with message like "the property 'name' is not defined".

### PR DESCRIPTION
**Pull request by tempo92**
Closes #6

### CODE REVIEW

File: src/main/java/org/tempo/springEdu/contoller/ProjectController.java [hunk 1]
```diff
@@ -60,4 +65,16 @@ String home() {
             ProjectNotFoundException exception) {
         return new ResponseEntity(exception.getMessage(), HttpStatus.NOT_FOUND);
     }
+
+    @ExceptionHandler({MethodArgumentNotValidException.class})
```
Comment (iv21dk) [inline src/main/java/org/tempo/springEdu/contoller/ProjectController.java:69]: I suggest to move to new bean like this `ExceptionHandler`

**Review by iv21dk — APPROVED** [review]

File: src/main/java/org/tempo/springEdu/contoller/ProjectController.java (hunk 1 above)
Comment (tempo92) [reply src/main/java/org/tempo/springEdu/contoller/ProjectController.java]: Fixed

**Review by iv21dk — APPROVED** [review]
